#!/bin/sh

destination='/usr/local/bin';
source='/usr/share/php/allunit/tools';

ln -s ${source}/createAuUser.php ${destination}/createAuUser
ln -s ${source}/createAuProject.php ${destination}/createAuProject